# Generated by Django 2.0 on 2021-12-28 12:28

import census.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='voter_id',
            field=models.PositiveIntegerField(validators=[census.validators.validation_census_voter_id]),
        ),
    ]
