# Generated by Django 2.0 on 2021-12-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='postproc_type',
            field=models.IntegerField(choices=[(1, 'Dhont'), (2, 'Borda'), (3, 'SaintLague')], default=1),
        ),
    ]
