# Generated by Django 2.0 on 2022-01-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20220107_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'IDENTITY'), (2, 'BORDA'), (4, 'EQUALITY'), ('DHONT', 'DHONT'), (3, 'SAINTE_LAGUE')], default=1),
        ),
    ]
