# Generated by Django 2.0 on 2021-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='url',
            field=models.URLField(default='http://localhost:8000/booth/', help_text='http://localhost:8000/booth/', max_length=40),
            preserve_default=False,
        ),
    ]
