# Generated by Django 2.0 on 2022-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20220107_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[('DHONT', 'DHONT'), (3, 'SAINTE_LAGUE'), (4, 'EQUALITY'), (0, 'IDENTITY'), (2, 'BORDA')], default=0),
        ),
    ]
