# Generated by Django 2.0 on 2021-12-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_postproc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='postproc_type',
            field=models.IntegerField(choices=[(2, 'Borda'), (1, 'Dhont'), (3, 'SaintLague')], default=1),
        ),
    ]
