# Generated by Django 2.0 on 2022-01-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20211217_1848'),
        ('voting', '0005_auto_20211218_1835'),
        ('voting', '0005_auto_20211219_1911'),
    ]

    operations = [
    ]
