# Generated by Django 2.0 on 2022-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20220107_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(3, 'SAINTE_LAGUE'), (0, 'IDENTITY'), (2, 'BORDA'), (4, 'EQUALITY'), (1, 'DHONT')], default=1),
        ),
    ]
