# Generated by Django 2.0 on 2022-01-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_merge_20220103_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='postproc_type',
            field=models.IntegerField(choices=[(1, 'Dhont'), (2, 'Borda'), (3, 'SaintLague')], default=1),
        ),
    ]
