# Generated by Django 2.0 on 2022-01-08 15:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20220107_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='tallyH',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='tallyM',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(3, 'SAINTE_LAGUE'), (1, 'DHONT'), (2, 'BORDA'), (0, 'IDENTITY'), (4, 'EQUALITY')], default=1),
        ),
    ]
