# Generated by Django 2.0 on 2022-01-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20220103_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='postproc_type',
            field=models.IntegerField(choices=[(1, 'Dhont'), (3, 'SaintLague'), (2, 'Borda')], default=1),
        ),
    ]
