# Generated by Django 2.0 on 2022-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20220108_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'IDENTITY'), (3, 'SAINTE_LAGUE'), (1, 'DHONT'), (4, 'EQUALITY'), (2, 'BORDA')], default=1),
        ),
    ]
