# Generated by Django 2.0 on 2022-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20220103_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='postproc_type',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(4, 'EQUALITY'), (1, 'DHONT'), (3, 'SAINTE_LAGUE'), (0, 'IDENTITY'), (2, 'BORDA')], default=1),
        ),
    ]
