# Generated by Django 2.0 on 2022-01-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20220108_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(2, 'BORDA'), (1, 'DHONT'), (3, 'SAINTE_LAGUE'), (0, 'IDENTITY'), (4, 'EQUALITY')], default=1),
        ),
    ]
