# Generated by Django 2.0 on 2022-01-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20220104_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'IDENTITY'), (2, 'BORDA'), (1, 'DHONT'), (4, 'EQUALITY'), (3, 'SAINTE_LAGUE')], default=1),
        ),
    ]
