# Generated by Django 2.0 on 2022-01-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20220104_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(4, 'EQUALITY'), (3, 'SAINTE_LAGUE'), (1, 'DHONT'), (2, 'BORDA'), (0, 'IDENTITY')], default=1),
        ),
    ]
