# Generated by Django 2.0 on 2022-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_auto_20220105_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'IDENTITY'), (1, 'DHONT'), (4, 'EQUALITY'), (3, 'SAINTE_LAGUE'), (2, 'BORDA')], default=1),
        ),
    ]
