# Generated by Django 2.0 on 2022-01-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_auto_20220105_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'IDENTITY'), (1, 'DHONT'), (4, 'EQUALITY'), (2, 'BORDA'), (3, 'SAINTE_LAGUE')], default=1),
        ),
    ]
