# Generated by Django 2.0 on 2022-01-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_auto_20220107_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'DHONT'), (3, 'SAINTE_LAGUE'), (0, 'IDENTITY'), (4, 'EQUALITY'), (2, 'BORDA')], default=1),
        ),
    ]
