# Generated by Django 2.0 on 2022-01-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_auto_20220107_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(2, 'BORDA'), (0, 'IDENTITY'), (4, 'EQUALITY'), (3, 'SAINTE_LAGUE'), (1, 'DHONT')], default=1),
        ),
    ]
