# Generated by Django 2.0 on 2022-01-07 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('suggesting_date', models.DateField()),
                ('content', models.TextField(max_length=4000)),
                ('send_date', models.DateField(default=datetime.date.today)),
                ('is_approved', models.NullBooleanField()),
            ],
        ),
    ]
