# Generated by Django 2.0 on 2022-01-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.PositiveSmallIntegerField(default=25),
            preserve_default=False,
        ),
    ]
