# Generated by Django 2.0 on 2021-12-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ip',
            field=models.CharField(default='Desconocido', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='region',
            field=models.CharField(default='Desconocida', max_length=200),
            preserve_default=False,
        ),
    ]
