# Generated by Django 2.0 on 2022-01-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211221_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.PositiveSmallIntegerField(default=18),
            preserve_default=False,
        ),
    ]
